### PR TITLE
Adds a prettier formatting check to the github actions

### PR DESCRIPTION
**Pull request by Jdban**
This adds a formatting check via prettier to the github actions.

I noticed some PRs were a bit hairy with formatting changes, this would help alleviate that.

### CODE REVIEW

**Comment by srsholmes** [comment]
@Chanzhaoyu I disagree with that strongly.

https://youtu.be/RAelLqnnOp0

This video from @t3dotgg sums up why nicely.

**Comment by Chanzhaoyu** [comment]
> 
Spending several minutes using CI just for formatting...

**Comment by Chanzhaoyu** [comment]
> @Chanzhaoyu I disagree with that strongly.
> 
> https://youtu.be/RAelLqnnOp0
> 
> This video from @t3dotgg sums up why nicely.

Spending several minutes using CI just for formatting...

**Comment by TommyE123** [comment]
I've also been looking into all of the formatting in general and was looking to do a PR with a fully automated solution to prevent future issues with formatting, styling and help catch errors in general across the whole repository.

But this PR beat me to it!!

I’ve also made pretty much a load of identical changes in my branch to what you’ve made, to clean up some of the issues since this was last done in a previous PR by @srsholmes only 3 days ago!

I however, have implemented [Mega-Linter](https://megalinter.io/latest/) which goes beyond just using prettier.

Using Mega-Linter is a good idea because it provides an all-in-one solution for linting multiple programming languages and formats, automatically checks your code for errors and vulnerabilities, is highly customizable, and works seamlessly with pull requests on GitHub. By using Mega-Linter, you can catch potential problems early on, maintain consistency across your codebase, and customize the linter rules to meet the specific needs of your project. Mega-Linter automatically runs on pull requests in GitHub, providing feedback directly in the pull request, making it easy to identify and address issues before merging. Moreover, Mega-Linter supports a wide range of customization options, so you can configure it to meet the specific needs of your project. Overall, using Mega-Linter can help improve code quality, maintain consistency across your codebase, and increase the efficiency of your development process.

Mega-Linter in my branch has caught a vast number of other issues that prettier is not designed to detect.
I think we have a few options to address this:

**Accept this PR fully.** 
This will make my future PR cleaner and prevent interim prettier issues arising. Then when I’m ready I’ll remove your prettier workflow and add the mega-linter workflow instead as part of my PR. However, would mean we would have a knowingly redundant workflow implemented.

**Accept this PR but without the workflow.** 
This will clean-up the files again but would leave us open to PRs with potential issues. However, would mean we don’t have a knowingly redundant workflow implemented.

**Wait for my PR.**
Not really my preferred approach as would make my PR easier and cleaner later! LOL

Obviously completely open to ideas and offers on what we think the best approach is. However, whichever way we go I’d suggest some sort of PR check to enforce some rules. Otherwise, as we are seeing now, developers are not formatting their code to certain standards and we will end up with a right old mishmash of coding styles and potential bugs and issues!

Hope this makes some sense!
Tom

**Comment by srsholmes** [comment]
> > @Chanzhaoyu I disagree with that strongly.
> > https://youtu.be/RAelLqnnOp0
> > This video from @t3dotgg sums up why nicely.
> 
> Spending several minutes using CI just for formatting...

Format on save and problem solved.

Don't stop people committing / contributing because of arbitrary rules.

The other thing is once you introduce a pre commit hook for formatting, it opens the gates for tests / linting and a load of other things which shouldn't stop me committing.

**Comment by srsholmes** [comment]
@TommyE123 does megalinter work within an IDE / can it be used alongside prettier? 

I think the benefits of auto formatting are not only for consistency but also to save the developers from having to format code.

It would be a shame to lose that.

Having external for matters which the IDE doesn't understand can lead to devx issues where files are updated externally, and it clashes with the local version on the IDE.

**Comment by mckaywrigley** [comment]
Can someone give me the TLDR of why something like this should be implemented over what we have now?

**Comment by Jdban** [comment]
> Can someone give me the TLDR of why something like this should be implemented over what we have now?

Right now, there's a prettier formatting file. This is basically just guidelines without any enforcement. Like a sign saying "stay off the grass" without a fence. 
With enforcement, there would actually be consistency in the code's formatting.

Changesets would be a lot cleaner with enforcement in place
For example, here's a recent small PR : https://github.com/mckaywrigley/chatbot-ui/pull/304/files
They changed 2 lines in this PR, with the second change being directly against the prettier formatting rules set for this project, and completely unnecessary.

There are a couple consequences to this:
1. The formatting in this file is now wrong
2. This changeset now includes extra lines, and another changeset for this file will likely contain the fix to this change. That is all unnecessary
3. It is less clear what the functional change is for a PR when there's extraneous unrelated formatting changes going in.

Here's another PR: https://github.com/mckaywrigley/chatbot-ui/pull/280/files
94 lines added, 38 removed.
At a glance, I can see that ~40 lines of the file were changed for formatting reasons and nothing else. 
Without this PR having to fix these formatting errors, it would be significantly clearer what the actual functional change is, making review much simpler and maintaining clarity.

Merging in a PR like this is going to be a bit of a pain initially, but there will be short and long-term benefits.

**Comment by mckaywrigley** [comment]
@Jdban And what's the pain initially with this?

Sorry for the questions! Just trying to learn here :)

**Comment by Jdban** [comment]
> And what's the pain initially with this?

One pain point is that I keep having to merge master into my branch and rerun prettier formatting to keep this updated :D

Another pain point is that people opening PRs in the near future after this gets merged might have conflicts due to this PR making lots of formatting changes. I guess that's already an issue though, and this essentially solves that issue permanently for the future though past some initial hiccups.

**Pull request closed without merging**
