### PR TITLE
add support for new gpt-3.5-turbo-16k model

### PR DESCRIPTION
**Pull request by Wnine16**

### CODE REVIEW

**Comment by Jdban** [comment]
sadly this repo is abandoned by the creator

**Comment by srsholmes** [comment]
Thanks for doing this. 

I have added it to my fork.

**Comment by Enkronan** [comment]
Thanks for this!

**Comment by juncodeworld** [comment]
> 遗憾的是这个仓库被创建者放弃了

为啥放弃了？有其他新的项目吗？

**Comment by anow2** [comment]
> sadly this repo is abandoned by the creator

Are there other repos that do this same thing that are being actively maintained?

**Pull request closed without merging**
