### PR TITLE
🆕 feat(LoginForm.tsx): add LoginForm component

### PR DESCRIPTION
**Pull request by Nimdy**
🆕 feat(LoginForm.tsx): add form validation with Formik
🆕 feat(LoginForm.tsx): add cookie handling with js-cookie
🆕 feat(_app.tsx): add isLoggedIn state to handle login status
🆕 feat(_app.tsx): add useEffect hook to check login status on mount
🆕 feat(_app.tsx): add LoginForm component to handle login
🆕 feat(package.json): add formik and js-cookie dependencies
🆕 feat(package.json): add @types/js-cookie dependency

**Create .env.production for these two variables:**
```
process.env.NEXT_PUBLIC_USERNAME=UserName
process.env.NEXT_PUBLIC_PASSWORD=Password
```

**leave .env and/or .env.local for these variables:**
```
DEFAULT_MODEL=gpt-3.5-turbo
DEFAULT_SYSTEM_PROMPT=You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.
OPENAI_API_KEY=YOUR_KEY

GOOGLE_API_KEY=YOUR_API_KEY
GOOGLE_CSE_ID=YOUR_ENGINE_ID
```

By default the LoginForm.tsx is set to bypass the LoginForm when entering a blank username and password, it can be enable or disabled with:

components/Settings/LoginForm.tsx:

Line 15:
```
const bypassAuth = true; // Set to true to enable bypass, set to false to disable bypass
```

### CODE REVIEW

**Comment by Nimdy** [comment]
Update with new PR to ensure latest REFACTOR changes do not conflict.

[QuickResolveAI](https://github.com/QuickResolveAI) [Jdban](https://github.com/Jdban) [dornfeld-capital](https://github.com/dornfeld-capital)  [rossman22590](https://github.com/rossman22590)

**Comment by Nimdy** [comment]
Updated the Login Form to be 100% env driven.

If this is pulled into main, I will add SSO options as well.

🔒 chore(LoginForm.tsx): remove bypassAuth variable initialization and…
… move it to component props
✨ feat(LoginForm.tsx): add support for bypassing authentication through component props
🔒 chore(_app.tsx): use environment variables for LoginForm component props instead of undefined values
```
# LoginForm Vars

# The username required for authentication in the LoginForm
# Add in .env.production
NEXT_PUBLIC_USERNAME=UserName

# The password required for authentication in the LoginForm
# Add in .env.production
NEXT_PUBLIC_PASSWORD=Password

# A boolean flag to enable or disable bypassing the LoginForm authentication
# Set to 'True' to bypass the login without entering any credentials
# Set to 'False' to require entering the correct username and password
# Add in .env.production
NEXT_PUBLIC_BYPASS_LOGIN=True


# Notes about Next.js and environment variables since I see a lot of confusion about this in the Issues Tab:
# Remember that Next.js will automatically load the appropriate .env.* files depending on the current environment:
#
# .env: Default environment variables for all environments
# .env.local: Local development environment variables (overrides the default)
# .env.development: Development environment variables (overrides both default and local)
# .env.development.local: Local development environment variables specific to development (overrides all)
# .env.production: Production environment variables (overrides both default and local)
# .env.production.local: Local development environment variables specific to production (overrides all)
```

**Comment by Nimdy** [comment]
image

**Comment by PureWhiteWu** [comment]
What's the current status of this PR?

Really looking forward for this to merge.

**Comment by nxtreaming** [comment]
Thanks, I deploy your patch, I found two bugs, please verify.

1)  `setIsLoggedIn(localStorage.getItem('isLoggedIn')` === `'true');` is wrong, it should be 
import Cookies from 'js-cookie';
...
setIsLoggedIn(Cookies.get('isLoggedIn') === 'true');

2) should check status: isLoading , otherwise, the login form could redraw per refresh even if user has logined

**Comment by nxtreaming** [comment]
How to tackle with a fake Cookie: isLoggedIn to bypass the login?

**Comment by Nimdy** [comment]
> How to tackle with a fake Cookie: isLoggedIn to bypass the login?

You would need to setup a server side app using JWT authentication:

First we would have to install a few more deps:

```
npm install express jsonwebtoken dotenv cors
```

The setup a JWT secret key:

```
JWT_SECRET=yoursecretkey
``` 

Then setup a JWT server app:

```
const express = require('express');
const jwt = require('jsonwebtoken');
const dotenv = require('dotenv');
const cors = require('cors');

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

app.post('/login', (req, res) => {
  const { username, password } = req.body;

  // Replace these with your actual credentials
  const validUsername = process.env.VALID_USERNAME;
  const validPassword = process.env.VALID_PASSWORD;

  if (username === validUsername && password === validPassword) {
    const token = jwt.sign({ username }, process.env.JWT_SECRET, { expiresIn: '1d' });
    res.status(200).json({ token });
  } else {
    res.status(401).json({ message: 'Invalid username or password.' });
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
```

The you would need to modify the LoginForm I created and replace the const handleSubmit function.

Add to top of LoginForm
```
import axios from 'axios'; // Don't forget to install axios: npm install axios
```

Replace handleSubmit function:
```
const handleSubmit = async (values: { username: string; password: string }) => {
  setIsLoading(true);

  if (bypassAuth && values.username.trim() === '' && values.password.trim() === '') {
    console.log('Bypassing authentication');
    Cookies.set('authToken', 'dummy_token', { expires: 1 });
    onLogin();
    setIsLoading(false);
    return;
  }

  try {
    const response = await axios.post('/login', {
      username: values.username,
      password: values.password,
    });

    if (response.status === 200) {
      console.log('Credentials match.');
      Cookies.set('authToken', response.data.token, { expires: 1 }); // Set the JWT token as a cookie
      onLogin();
    }
  } catch (error) {
    if (error.response.status === 401) {
      console.log('Credentials do not match.');
      toast.error('Invalid username or password.');
    } else {
      console.log('An error occurred.');
      toast.error('An error occurred. Please try again.');
    }
  }

  setIsLoading(false);
};
```

Then update the  _app.tsx file:

```
import { Toaster } from 'react-hot-toast';
import { QueryClient, QueryClientProvider } from 'react-query';

import { appWithTranslation } from 'next-i18next';
import type { AppProps } from 'next/app';
import { Inter } from 'next/font/google';

import LoginForm from '../components/Settings/LoginForm';
import Cookies from 'js-cookie';

import { useState, useEffect } from 'react';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });
const isBrowser = typeof window !== 'undefined';

function App({ Component, pageProps }: AppProps<{}>) {
  const queryClient = new QueryClient();

  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    if (isBrowser) {
      setIsLoggedIn(!!Cookies.get('authToken')); // Update this line to check for the 'authToken' cookie
    }
  }, []);

  if (!isLoggedIn) {
    // If the user is not logged in, show the login form
    return (
      <LoginForm
        onLogin={() => setIsLoggedIn(true)}
        username={process.env.NEXT_PUBLIC_USERNAME}
        password={process.env.NEXT_PUBLIC_PASSWORD}
        bypassAuth={process.env.NEXT_PUBLIC_BYPASS_LOGIN === 'true'}
      />
    );
  }

  return (
    <div className={inter.className}>
      <Toaster />
      <QueryClientProvider client={queryClient}>
        <Component {...pageProps} />
      </QueryClientProvider>
    </div>
  );
}

export default appWithTranslation(App);
```

I can add this and it will work... just need to have the system run another service.

**Comment by Nimdy** [comment]
> How to tackle with a fake Cookie: isLoggedIn to bypass the login?

Now to answer the question to prevent bypassing with a fake cookie:

We have to add another package to the package.json:
```
npm install jsonwebtoken
```

Create a new function called isTokenValid and place it in a new file called utils/tokenUtils.ts
```
// utils/tokenUtils.ts
import jwt from 'jsonwebtoken';

export const isTokenValid = (token: string | undefined): boolean => {
  if (!token) {
    return false;
  }

  try {
    jwt.verify(token, process.env.NEXT_PUBLIC_JWT_SECRET as string);
    return true;
  } catch (error) {
    console.error('Token verification failed:', error);
    return false;
  }
};
```

Then update the _app.tsx file with:

Add to the top
```
import { isTokenValid } from '../utils/tokenUtils';
```

Replace useEffect:
```
  useEffect(() => {
    if (isBrowser) {
      setIsLoggedIn(isTokenValid(Cookies.get('authToken'))); // Verify the token using the utility function
    }
  }, []);
```

Now, when the application checks for the 'authToken' cookie, it will also verify whether it's a valid JWT token signed with the server's secret key. If the token is invalid or has been tampered with, the user will be considered logged out, and the login form will be displayed.

**Comment by Nimdy** [comment]
I am not sure how much McKay wants to add to the over all application

**Comment by nxtreaming** [comment]
I think your method is wrong:
if (isBrowser)
  setIsLoggedIn(isTokenValid(Cookies.get('authToken'))); 

is the code executed in client(browser)? if yes, it's wrong

User can get the secretKey: process.env.NEXT_PUBLIC_JWT_SECRET in client(web browser) due to isTokenValid() is called in client.

So this method is totally wrong here.

**Comment by Nimdy** [comment]
@nxtreaming https://github.com/Nimdy/chatgpt-menu-installer

I just made a whole installer to do everything. If McKay uses it, then he can add everything I have done.  I also have completed the other items you highlighted.  Tell me what you think. Maybe McKay can take it all and put it together.

**Pull request closed without merging**
