### PR TITLE
docker build action

### PR DESCRIPTION
**Pull request by tatsu-i**
Added github actions for docker image builds https://github.com/mckaywrigley/chatbot-ui/issues/92

### CODE REVIEW

**Comment by mckaywrigley** [comment]
Is there anything I need to do on my end to get this to work?

**Comment by tatsu-i** [comment]
> 

@mckaywrigley  You should be able to push docker images to ghcr.io automatically after merging into the main branch without setting any tokens or other secrets.

I have confirmed this in my personal repository below.
https://github.com/tatsu-i/chatbot-ui/pkgs/container/chatbot-ui

**Comment by mckaywrigley** [comment]
Does `secrets.GITHUB_TOKEN` expose anything from my account, or how does that work?

**Comment by tatsu-i** [comment]
GITHUB_TOKEN is a special access token that can be used to authenticate GitHub Actions on behalf of GitHub; GitHub automatically creates a GITHUB_TOKEN secret that can be used for authentication during workflow execution.
Github Actions will automatically generate the secrets temporarily without the need to configure Secrets, and GITHUB_TOKEN will disappear after the github actions execution is complete.

Below is my secrets settings screen, showing that the workflow is successful even though no token is set.

スクリーンショット 2023-03-26 23 34 27

**Comment by mckaywrigley** [comment]
Wonderful work!

**Pull request merged**
