### PR TITLE
add Groq LLaMA3 70B support llama3-70b-8192

### PR DESCRIPTION
**Pull request by faraday**
add Groq LLaMA3 70B support for endpoint: llama3-70b-8192
available at: https://console.groq.com/playground?model=llama3-70b-8192

### CODE REVIEW

**Comment by spammenotinoz** [comment]
Thanks works well

**Comment by SaidTorres3** [comment]
Did they change the pricing or it's wrong?
image
image

**Comment by faraday** [comment]
@SaidTorres3 It's wrong, your figures are right. I'll push correct figures.
Do you know where the costs are appearing when using chatbot-ui?

**Comment by SaidTorres3** [comment]
[lib/models/llm/groq-llm-list.ts](https://github.com/faraday/chatbot-ui/blob/70b48843386b3922850c63b223dfcf3bce464887/lib/models/llm/groq-llm-list.ts)

They appear hovering over the model name:
image

**Comment by faraday** [comment]
@SaidTorres3 Thank you, here's a PR for the fix of cost.
https://github.com/mckaywrigley/chatbot-ui/pull/1706

**Pull request merged**
