### PR TITLE
Bugfix: Work with multiple Azure model deployments

### PR DESCRIPTION
**Pull request by stainboy**
The original code always uses ${AZURE_DEPLOYMENT_ID} to invoke Azure OpenAI, which prevents users to work with multiple OpenAI models (e.g. 3.5 or 4).

The fix is to allow users to work with Azure OpenAI based on the selection.

### CODE REVIEW

**Comment by stainboy** [comment]
@mckaywrigley, could you take a look and get the fix merged? Thanks.

**Comment by Jdban** [comment]
> @mckaywrigley, could you take a look and get the fix merged? Thanks.

Don't get your hopes up, he's abandoned this repo

**Comment by Sudharma** [comment]
Does this also enables to work with multiple model deployments?

@Jdban No others can approve it?

**Comment by Jdban** [comment]
> 1 workflow awaiting approval
> This workflow requires approval from a maintainer.

Only one person is a maintainer, and he's abandoned the repo

**Comment by stainboy** [comment]
> Does this also enables to work with multiple model deployments?

Yes, it does help to work with multiple model deployments. (I will change the PR subject to reflect the impact)

**Pull request closed without merging**
