### PR TITLE
feat: next-auth -  email pattern matching only

### PR DESCRIPTION
**Pull request by dotneet**
This is very simple NextAuth implementation.
But for some people including me this will be enough.

This implementation uses only JWT and email patterns for authentication.

### CODE REVIEW

**Comment by pdgxiaofei** [comment]
hello
Excuse me, how do you need to use this, I inherited your branch, and the startup project authentication does not work. I have filled in the required parameters.
Thank you very much if you can answer

**Comment by kyleroberts-ai** [comment]
> hello
> Excuse me, how do you need to use this, I inherited your branch, and the startup project authentication does not work. I have filled in the required parameters.
> Thank you very much if you can answer

Have the same problem

**Comment by dotneet** [comment]
Adding console.log to middleware.ts would provide insight.

**Comment by dotneet** [comment]
@pdgxiaofei @QuickResolveAI 
sorry, I've fixed the problem that maybe you've encountered.
please try again.

**Pull request closed without merging**
