### PR TITLE
Refacto ollama list

### PR DESCRIPTION
**Pull request by wrapss**
Update on how to retrieve the list of ollama models

### CODE REVIEW

**Comment by Bortus-AI** [comment]
Thanks for this fix.

**Review by Bortus-AI — APPROVED** [review]

**Comment by mysterium-coniunctionis** [comment]
Just installed Chatbot-UI and it looks great but I'm running into the same issue and I'm not sure how to fix it. Do I need to reinstall from scratch or run and update?

**Comment by wrapss** [comment]
> Just installed Chatbot-UI and it looks great but I'm running into the same issue and I'm not sure how to fix it. Do I need to reinstall from scratch or run and update?

what is ur problem ?

**Comment by mckaywrigley** [comment]
@wrapss Great contribution. Much better implementation. I think this fixes some bugs for users as well. Made a minor syntax change but otherwise merged. Thanks for joining the contributor's list!

**Pull request closed without merging**
