### PR TITLE
Solve the garbled issue of Chinese/Japanese/Korean

### PR DESCRIPTION
**Pull request by xycjscs**
this pull request is to solve issues mentioned at https://github.com/mckaywrigley/chatbot-ui/issues/1171#issuecomment-1913188903

This is my first contribution. I am happy to share my excitement with you.

At first, we thought it may be resulted from the combo of Vercel and OpenAi. However, I checked the Vercel/Ai repo, and this problem has been address before. I deployed the openai example of Vercel/ai repo at vercel. It could deal with Chinese language pretty well. I believe it is a bug.

I dived into this project to find where the bug is. Characters are returned by chunk, so I add "1" between each chunk.
Screenshot 2024-01-28 at 12 06 41 AM
Clearly, the chunk is not complete, and the garble issue happens. 

Then, I found the decode function of each chunk  `callback(decoder.decode(value))` at the lib/consume-stream.ts
This function was mentioned in this issue. 
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/507

I believe, following correction can solve problem:
`callback(decoder.decode(value, { stream: true }))`

After testing. There is no more garbled issues.

Screenshot 2024-01-28 at 12 12 33 AM

People who deployed project at Netlify and files uploading issues happened, could keep using Vercel with this commit. 
https://github.com/mckaywrigley/chatbot-ui/issues/1283#issuecomment-1912350380

### CODE REVIEW

**Comment by xycjscs** [comment]
？？ issue in https://github.com/mckaywrigley/chatbot-ui/issues/1147 could also be solved.

**Comment by xycjscs** [comment]
Validations on Japanese/Korea
IMG_2160
IMG_2159

**Comment by xycjscs** [comment]
Validation on Russia, in case others searched with Russia keyword 
IMG_2161

**Comment by mckaywrigley** [comment]
You are a hero.

**Pull request merged**
