### PR TITLE
Fix Process Docx Bug

### PR DESCRIPTION
**Pull request by hikafeng**
add new function
createFileBasedOnExtension

### CODE REVIEW

**Comment by mckaywrigley** [comment]
What bug does this fix?

There is a `createDocXFile` funciton that should be handling the docx files.

**Comment by hikafeng** [comment]
You can try to upload, you will find that uploading DOCX files will fail, the reason is that some functions are missing.

**Comment by hikafeng** [comment]
The reason is that the unmodified components/sidebar/items/all/sidebar-create-item.tsx file directly calls the const createdFile = await createFile function, which is used to process non-DOCX files. When uploading a DOCX file, calling createFile will obviously fail because it is not designed to handle DOCX files.

**Comment by mckaywrigley** [comment]
Got it. Will merge and nice catch.

**Pull request merged**
