### PR TITLE
[bugfix] Firefox experiences CJK IME issues due to CompositionEvent.

### PR DESCRIPTION
**Pull request by ryanhex53**
Related to PR #253, fixes an issue with Chinese input not working properly in Firefox. Fixes issue #218

### CODE REVIEW

**Comment by ryanhex53** [comment]
Before
before

After
after

**Comment by liby** [comment]
1. The issue was introduced by #4, not #253. This can be confirmed by looking at the [issue](https://github.com/mckaywrigley/chatbot-ui/issues/218) creation time and the PR merging time.
2. The PR doesn't explain why it causes the inability to input Chinese characters:
    - The main reason for this issue is the differing behavior of the `onCompositionEnd` event in Firefox compared to other browsers. The specific reason can be found at https://github.com/w3c/uievents/issues/202.
    - TL;DR, in Firefox, the "input" event is fired after "compositionend".
3. There are two potential issues when using the `onKeyUp` event to handle Chinese input:
   1. Delayed response: The `onKeyUp` event is triggered when a key is released, which may lead to delays in determining the input state. For example, when selecting a suggested word shown by the input method, there may be a delay during the selection process after pressing the space key.
   2. Inaccurate input state: In practice, to accurately handle the input method editing state, it's important to know whether the current input is input method editing or other input. In some cases (such as continuous keypresses), the `onKeyUp` event may be triggered before input event handling finishes, leading to inaccuracies in determining the input method editing state.

**Comment by ryanhex53** [comment]
@liby Fine, Could you fix your code to solve the problem of inputting Chinese characters in Firefox? Because as long as `onCompositionStart` or `onCompositionEnd` is used, inputting cannot be done normally in Firefox. It took me several hours to figure out the problem and get it to a usable and functional state.

**Comment by ryanhex53** [comment]
closed by mistake, should reopen this.

**Pull request closed without merging**
