### PR TITLE
feature: add login form set env with variables

### PR DESCRIPTION
**Pull request by Nimdy**
Added simple login form. Set .env.local vars 

Create .env.production for these two variables:

process.env.NEXT_PUBLIC_USERNAME;
process.env.NEXT_PUBLIC_PASSWORD;

leave .env and/or .env.local for these variables:

# Chatbot UI
DEFAULT_MODEL=gpt-3.5-turbo
DEFAULT_SYSTEM_PROMPT=You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.
OPENAI_API_KEY=YOUR_KEY

# Google
GOOGLE_API_KEY=YOUR_API_KEY
GOOGLE_CSE_ID=YOUR_ENGINE_ID

Add file:
components/Settings/LoginForm.tsx

Updated file:
pages/_app.tsx

Added package to package.json:   formik

Default Username and Password:

Username = test
Password = test

By default the LoginForm.tsx is set to bypass the LoginForm when entering a blank username and password, it can be enable or disabled with:

components/Settings/LoginForm.tsx:

Line 14:
```
const bypassAuth = true; // Set to true to enable bypass, set to false to disable bypass
```

### CODE REVIEW

**Comment by dornfeld-capital** [comment]
@Nimdy  Do you have steps to test a login in the vercel preview deployment?

**Comment by rossman22590** [comment]
also, if you leave blank is login no longer required?

**Review by Nimdy — COMMENTED** [review]
[dornfeld-capital](https://github.com/dornfeld-capital)
[rossman22590](https://github.com/rossman22590)

tweaked and remove unneeded code for LoginForm.tsx and _app.tsx

Here is how I got it all working:

.env holds:

DEFAULT_MODEL=whatever
OPENAI_API_KEY=whatever
DEFAULT_SYSTEM_PROMPT=whatever

make

.env.production

NEXT_PUBLIC_USERNAME=username
NEXT_PUBLIC_PASSWORD=password

My docker-compose.yml:

version: '3.8'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - DEFAULT_SYSTEM_PROMPT=${DEFAULT_SYSTEM_PROMPT}
      - NEXT_PUBLIC_USERNAME=${NEXT_PUBLIC_USERNAME}
      - NEXT_PUBLIC_PASSWORD=${NEXT_PUBLIC_PASSWORD}



My Dockerfile:

No changes.

**Comment by Nimdy** [comment]
> @Nimdy Do you have steps to test a login in the vercel preview deployment?

I suppose, if I created a .env.production file with the test it would work... Let me try that real fast and make a PR.

username: test
password: test

**Comment by Nimdy** [comment]
> also, if you leave blank is login no longer required?

You can add a conditional check at the beginning of the handleSubmit function to bypass the login process if both the username and password are blank. Here's the modified LoginForm component:

```
export default function LoginForm({ onLogin, username, password }: Props) {
    const [isLoading, setIsLoading] = useState(false);

    const handleSubmit = async (values: { username: string, password: string }) => {
        setIsLoading(true);

        // Check if the entered username and password match the ones from the .env file
        if ((values.username === username && values.password === password) || (values.username === '' && values.password === '')) {
            console.log('Credentials match.');
            localStorage.setItem('isLoggedIn', 'true');
            localStorage.setItem('username', values.username);
            onLogin();
        } else {
            console.log('Credentials do not match.');
            console.log('Username: ' + values.username);
            console.log('Password: ' + values.password);

            // If the authentication fails, show an error message
            toast.error('Invalid username or password.');
        }

        setIsLoading(false);
    };
}
```

**Comment by Nimdy** [comment]
Updated LoginForm to clear checks... Took one too many lines out... oops

**Comment by Nimdy** [comment]
> @Nimdy Do you have steps to test a login in the vercel preview deployment?
[dornfeld-capital](https://github.com/dornfeld-capital)
[rossman22590](https://github.com/rossman22590)
The preview access is:

username: test
password: test

Preview is working. Enjoy!

I have to go to bed... see you all tomorrow

**Comment by rossman22590** [comment]
you should include this in the commit by default :)

**Comment by Nimdy** [comment]
> rossman22590

Here you go. I added it for you ;)
```
export default function LoginForm({ onLogin, username, password }: Props) {
  const [isLoading, setIsLoading] = useState(false);

  const bypassAuth = true; // Set to true to enable bypass, set to false to disable bypass

  const handleSubmit = async (values: { username: string; password: string }) => {
    setIsLoading(true);

    if (
      bypassAuth &&
      values.username.trim() === '' &&
      values.password.trim() === ''
    ) {
      console.log('Bypassing authentication');
      localStorage.setItem('isLoggedIn', 'true');
      onLogin();
      setIsLoading(false);
      return;
    }

    // Check if the entered username and password match the ones from the .env file
    if (values.username === username && values.password === password) {
      console.log('Credentials match.');
      localStorage.setItem('isLoggedIn', 'true');
      localStorage.setItem('username', values.username);
      onLogin();
    } else {
      console.log('Credentials do not match.');
      // If the authentication fails, show an error message
      toast.error('Invalid username or password.');
    }

    setIsLoading(false);
  };
 ```
  With this modification, when bypassAuth is set to true, entering a blank username and password will bypass the login auth check. To disable this feature, set bypassAuth to false.

**Comment by dornfeld-capital** [comment]
It would be good to add 
- An environment variable that defaults to false to disable the login modal
- A logout button in the menu

Also, this method is insecure. You can set `localStorage.setItem('isLoggedIn' true)` to bypass the login modal.

**Comment by Nimdy** [comment]
removed

> It would be good to add
> 
> * An environment variable that defaults to false to disable the login modal
> * A logout button in the menu
> 
> Also, this method is insecure. You can set `localStorage.setItem('isLoggedIn' true)` to bypass the login modal.


Added js-cookie to package.json and package-lock.json

Remove local storage for handling login after auth

Updated file:
components/Settings/LoginForm.tsx

Removed local storage and added logic for handle cookie session login


Updated file:
pages/_app.tsx

Added logic to process cookie based auth

I can add a logout button but keep working on other items but I have to wait to see what @mckaywrigley does.  I coded this to be as compartmentalized as possible.  If this get added... I will add more options but mckaywrigley is moving very fast and I am not trying to redo a bunch of stuff or overlap on his code base.

I see a lot of people help to compartmentalize everything and that is a good thing... then I will add more.

**Comment by Jdban** [comment]
Did you mean to add a yarn lock file? Seems like it shouldn't be added to the repo.

**Comment by Nimdy** [comment]
> Did you mean to add a yarn lock file? Seems like it shouldn't be added to the repo.

gosh no...  removing it... I have so many terminals open... thank you

**Comment by kyleroberts-ai** [comment]
Hi @Nimdy, could you update the code to work with the new main branch. I believe the code has been refactored. Be really handy to get this working

**Comment by Nimdy** [comment]
updating

**Pull request closed without merging**
