### PR TITLE
Fix model switcher for Azure

### PR DESCRIPTION
**Pull request by itbm**
Reverts mckaywrigley/chatbot-ui#499

I suggest reverting this as it isn't necessary and breaks model switching between GPT-3.5, GPT-4 and GPT-4-32K in the UI. Should be merged with #509.

See https://github.com/mckaywrigley/chatbot-ui/issues/498#issuecomment-1503808802

### CODE REVIEW

**Comment by kleptog** [comment]
This isn't correct. The deployment name in the URL is unrelated to the model name and must be configured. I don't think there is a way to get a list of available deployments unless you can access the Azure API.

**Comment by itbm** [comment]
@kleptog it is correct. The azure api returns both the model name and the deployment name. The code already checks against the model (model field), then translates it to the deployment name (id field) for use in the URL.

See https://github.com/mckaywrigley/chatbot-ui/blob/main/pages/api/models.ts#L53.

With this PR it doesn't matter what the deployment is called, as it looks for the model and updates the URL accordingly.

**Comment by itbm** [comment]
@mckaywrigley I’ve fixed merge conflicts. Would it be possible to get this reviewed and merged?

**Comment by ivanfioravanti** [comment]
This works! Great job @itbm

**Comment by brandco** [comment]
It looks like the Azure deployment name would need to match the model name for this to work. Is that correct? 

I'm not sure why someone would use a deployment name that doesn't match the model name in setting up Azure OpenAI, but it is possible. Perhaps this is useful for fine tuned models, I'm not sure.

**Comment by itbm** [comment]
With this PR they can be different. Chatbot UI will use the model name internally up until it makes the request to Azure, at which point it will use the deployment name in the URL.

**Comment by tobigue** [comment]
Currently always the default model (configured in `AZURE_DEPLOYMENT_ID`) is used instead of the model the user picked in the interface when using Azure as backend, so would be great to get this merged! :)

**Comment by Kush-agra-wal** [comment]
> It looks like the Azure deployment name would need to match the model name for this to work. Is that correct?
> 
> I'm not sure why someone would use a deployment name that doesn't match the model name in setting up Azure OpenAI, but it is possible. Perhaps this is useful for fine tuned models, I'm not sure.

Still facing this issue, when deployment name is not = model name the default model assigned at start of conversation is not assigning the model id from azure instead gives fallback one. if one of the deployments is named gpt-35-turbo it is able to work fine for other deployments which dont have name same as model name

**Pull request closed without merging**
