### PR TITLE
CopilotTextarea

### PR DESCRIPTION
**Pull request by ataibarkai**
Added CopilotTextarea to the send form.
It's given the entire existing conversation as context to inform autocompletions.

chatbot-ui-copilottextarea-lowres

### CODE REVIEW

**Comment by ataibarkai** [comment]
@mckaywrigley thoughts? 

the code changes are actually very minimal (most of the displayed line changes are from the .lock file)

**Comment by Bortus-AI** [comment]
This is great. Hopefully gets merged

**Comment by VerisimilitudeX** [comment]
Is this project dead?

**Comment by ataibarkai** [comment]
if you're asking about CopilotTextarea, it's very much alive at
https://github.com/RecursivelyAI/CopilotKit

**Comment by VerisimilitudeX** [comment]
No, I was referring to ChatBotUI. CopilotTextarea seems very cool thought! I'll be integrating it soon in https://github.com/VerisimilitudeX/DNAnalyzer

**Pull request closed without merging**
