### PR TITLE
feat: Add i18n support for Chinese language

### PR DESCRIPTION
**Pull request by Jungley8**
In the public/locales directory, create a subdirectory for each language you want to support (e.g., en, de, fr, es). Inside each subdirectory, create a JSON file for each namespace (e.g., common.json, home.json) containing the translations for that language.

### CODE REVIEW

**Comment by mckaywrigley** [comment]
This is incredible! Everything looks very clean too. This is a huge step in us being able to support the entire world. Thanks so much for this.

**Comment by mckaywrigley** [comment]
(ps... mind resolving the merge conflict? haha)

**Comment by mckaywrigley** [comment]
And i suppose the best way to keep the translations up to date is rely on community mostly, yeah?

**Comment by Jungley8** [comment]
> And i suppose the best way to keep the translations up to date is rely on community mostly, yeah?

Yes, relying on the community is often a great way to keep translations up to date, especially for open-source projects. Engaging with the community can help ensure that translations remain accurate and relevant as your project evolves. To maintain up-to-date translations.  (answered by ChatGPT)

**Comment by Jungley8** [comment]
It seems to be not working in the Preview environment.

**Comment by mckaywrigley** [comment]
> 

Trying with 'zh' as defaultLocale and it doesn't seem to be working. Maybe a slight error in the config?

**Comment by Jungley8** [comment]
https://chatbot-qtawokyzt-mckay-personal.vercel.app/zh

It's now working in the preview environment.  @mckaywrigley

**Comment by mckaywrigley** [comment]
Working on my end. Merging. Thanks again for helping expand to international support! :)

**Comment by Jungley8** [comment]
> Working on my end. Merging. Thanks again for helping expand to international support! :)

My pleasure!

**Pull request merged**
