### PR TITLE
feature: Multiple Database Support + Multiple Accounts Support + Data Syncing

### LINKED ISSUE #147: Request -- Possible saving History via SQL for cpanel server
Could you please add SQL to store chat histories? Each conversation must be assigned a UUID and saved in the SQL database. The URL for the chat should be generated as it does on GPT chat. Chat conversations must be stored in the SQL database and if a user wants to export them, he can do so via a .json file. Also, if a user wants to import conversations, they can be automatically saved in the SQL database.

Thanks.
Jordon

### LINKED ISSUE #182: Add MongoDB database support for ChatBOT UI app
Currently, the ChatBOT UI app uses local storage to store chat messages. While this works fine for small-scale testing, it is not a scalable solution for real-world use cases. It would be great if the app could be updated to use a more robust and scalable database like MongoDB.

Adding support for MongoDB would not only improve the app's performance and reliability but also make it more attractive to users who need to store large volumes of chat messages. MongoDB is a popular choice for many web applications due to its scalability and flexibility, and it would be a valuable addition to the ChatBOT UI app.

### LINKED ISSUE #452: Cross device
Access chat history on other devices

### LINKED ISSUE #461: Implement persistent database storage for chat history and properties
Currently, chat history and properties are stored in the browser's local storage, which means they are not shared between devices and may be lost if the browser's cache is cleared.
I suggest implementing a persistent database to store chat history and things such as custom prompts and future configurations, so that users can access their data across multiple devices, and the data is not lost when the browser's cache is cleared.
Export and Import data manually is a nice feature  but this is not as user-friendly and convenient a database.
Please let me know your thoughts on this idea, and if you would be open to implementing it or accepting a pull request for this feature.

### LINKED ISSUE #620: RDBMS and multiple user accounts support
I am working on implementing RDBMS support using TypeORM. This means support for Postgres, MySQL, MariaDB, etc. At the same time, I am implementing an authentication system based on username and passwords to support multiple users inside the database.

My main issue right now is deciding whether a full username and password authentication system is even required. It would be really nice to just paste the API key and have all your data automatically pop up. However, as far as I know, there is no way of doing this without storing the API key in the database insecurely (raw, or hashed with a const salt).

I would appreciate any suggestions, guidance, collaboration, or other important information. Thanks.

### LINKED ISSUE #630: Where and how is the data saved?
Just too clarify, where and how is the data saved on handled from api to server?

### PR DESCRIPTION
**Pull request by jorge-menjivar**
## Relational Databases
Uses [TypeORM](https://github.com/typeorm/typeorm) to implement support for PostgreSQL and MySQL.
Support for MariaDB and CockroachDB is suspected but untested.

## CouchDB
Includes the work done in #561 which implements support for CouchDB.

## Multiple Account Support
Includes the work done in #560 to implement support for multiple user accounts in a single device **when used in conjunction with a relational database** as the storage method.

## Syncing Across Devices
By using a relational database as the storage method, now you can save and sync all data, excluding API Keys, across devices, as long as you use the same email to log in in each device.

A live version of this work, using PostgreSQL on google cloud as storage, can be found [here](https://chat.jmenjivar.com).

### Closes the following Issues
closes #630 
closes #620
closes #452
partial #659
partial #654

Plus a few closed by the work of #561 
closes #461
closes #182
closes #147
partial #367

### CODE REVIEW

**Comment by maddyonline** [comment]
Is there a documentation on how to use RDBMS? I see the Dockerfile only has setup for couchdb.

**Comment by eyefiy** [comment]
> Is there a documentation on how to use RDBMS? I see the Dockerfile only has setup for couchdb.

I second this. Need a tutorial to set as the live demo using PostgreSQL on my own google cloud as storage.

**Comment by jorge-menjivar** [comment]
@maddyonline @eyefiy Sorry for the delayed reply, I've been busy improving the work done here to allow for further customization from the community. This includes making a build-time extension system so that databases and authentication solutions can easily be swapped before deployment. 

- I've moved the RDBMS work into [its own extension](https://github.com/jorge-menjivar/chatbot-ui-rdbms), which now includes instructions just for RDBMS.

- I've moved the NextAuth work into [its own extension](https://github.com/jorge-menjivar/chatbot-ui-authjs) as well, which also includes instructions on setting it up.

Although I still need to polish this work before making a pull request, I would strongly encourage you to use the new extension system as it was specifically done to make it easier for developers to build more tools for Chatbot UI. You can use the [live branch of my repo](https://github.com/jorge-menjivar/chatbot-ui/tree/live), which is already being used for [production on my website](https://chat.jmenjivar.com) and it has these extensions already installed.

Regarding Docker, I have updated the [README](https://github.com/jorge-menjivar/chatbot-ui/tree/live#readme) with new instructions to build using docker.

**Comment by jorge-menjivar** [comment]
Also, if you encounter any issues with docker, please open a new issue in my fork. Thank You!

**Comment by maddyonline** [comment]
Thanks @jorge-menjivar. I like you managed to abstract out the RDBMS functionality into it's own plugin. For Docker, what would be helpful is if there is a docker-compose up command which sets up Postgres and chatbot-ui so as an end user one can have a functioning app running. From that point on, I think we can figure out how to deploy or how to modify for our use cases.

**Comment by eyefiy** [comment]
> @maddyonline @eyefiy Sorry for the delayed reply, I've been busy improving the work done here to allow for further customization from the community. This includes making a build-time extension system so that databases and authentication solutions can easily be swapped before deployment.
> 
> * I've moved the RDBMS work into [its own extension](https://github.com/jorge-menjivar/chatbot-ui-rdbms), which now includes instructions just for RDBMS.
> * I've moved the NextAuth work into [its own extension](https://github.com/jorge-menjivar/chatbot-ui-authjs) as well, which also includes instructions on setting it up.
> 
> Although I still need to polish this work before making a pull request, I would strongly encourage you to use the new extension system as it was specifically done to make it easier for developers to build more tools for Chatbot UI. You can use the [live branch of my repo](https://github.com/jorge-menjivar/chatbot-ui/tree/live), which is already being used for [production on my website](https://chat.jmenjivar.com) and it has these extensions already installed.
> 
> Regarding Docker, I have updated the [README](https://github.com/jorge-menjivar/chatbot-ui/tree/live#readme) with new instructions to build using docker.

Many thanks for your efforts. I'll definitely try it out. With your work plus a little adjustment, I believe it could apply to my team's workflow. Thanks a lot.

**Comment by datlife** [comment]
@jorge-menjivar is there any reasons why you removed the plugins?

**Pull request closed without merging**
