### PR TITLE
refactor(components): extend config with custom color

### PR DESCRIPTION
**Pull request by mattnorris**
Hello! 👋

Excellent work with this project! It's feature rich, and more than a clone. You've added delightful functionality that extends ChatGPT and adds true value. 

I started simple to understand the project structure. I noticed that the code may benefit from extending the color configuration to allow people to theme the application. I refactored the repeated color #343541 into the config. I also provided the naming rationale in the docs. 

If this change makes sense, I can continue with the other custom colors. I can submit them one at a time, or all at once - whatever is easiest to review.

### CODE REVIEW

**Comment by Jdban** [comment]
Just a heads up, @mckaywrigley abandoned the project over a month ago and hasn't merged any PRs or responded to anything about the project in a long time.

**Comment by mattnorris** [comment]
@Jdban thank you for the heads-up. That's too bad. It has real potential for customized apps.

**Comment by superpoussin22** [comment]
this one is active with some great improvement like token estimation ...
https://github.com/Shopify/chatbot-ui

**Comment by mattnorris** [comment]
Thanks, @superpoussin22 !

**Pull request closed without merging**
