### PR TITLE
Add CouchDB persistent storage

### LINKED ISSUE #147: Request -- Possible saving History via SQL for cpanel server
Could you please add SQL to store chat histories? Each conversation must be assigned a UUID and saved in the SQL database. The URL for the chat should be generated as it does on GPT chat. Chat conversations must be stored in the SQL database and if a user wants to export them, he can do so via a .json file. Also, if a user wants to import conversations, they can be automatically saved in the SQL database.

Thanks.
Jordon

### LINKED ISSUE #182: Add MongoDB database support for ChatBOT UI app
Currently, the ChatBOT UI app uses local storage to store chat messages. While this works fine for small-scale testing, it is not a scalable solution for real-world use cases. It would be great if the app could be updated to use a more robust and scalable database like MongoDB.

Adding support for MongoDB would not only improve the app's performance and reliability but also make it more attractive to users who need to store large volumes of chat messages. MongoDB is a popular choice for many web applications due to its scalability and flexibility, and it would be a valuable addition to the ChatBOT UI app.

### LINKED ISSUE #461: Implement persistent database storage for chat history and properties
Currently, chat history and properties are stored in the browser's local storage, which means they are not shared between devices and may be lost if the browser's cache is cleared.
I suggest implementing a persistent database to store chat history and things such as custom prompts and future configurations, so that users can access their data across multiple devices, and the data is not lost when the browser's cache is cleared.
Export and Import data manually is a nice feature  but this is not as user-friendly and convenient a database.
Please let me know your thoughts on this idea, and if you would be open to implementing it or accepting a pull request for this feature.

### PR DESCRIPTION
**Pull request by itbm**
Closes #461 
Closes #182 
Closes #147 
Partial #367

### CODE REVIEW

**Comment by amaanr** [comment]
Do you think a similar solution would work for Firebase? Haven't tried it yet but thought I would before venturing off.

**Comment by kyleroberts-ai** [comment]
> Do you think a similar solution would work for Firebase? Haven't tried it yet but thought I would before venturing off.

I second this

**Comment by jorge-menjivar** [comment]
@itbm I used your commit to add support for relational databases. Would you mind checking that I didn't break anything that you implemented? Thanks

https://github.com/jorge-menjivar/chatbot-ui/tree/rdbms_storage

**Comment by itbm** [comment]
> @itbm I used your commit to add support for relational databases. Would you mind checking that I didn't break anything that you implemented? Thanks
> 
> https://github.com/jorge-menjivar/chatbot-ui/tree/rdbms_storage

@jorge-menjivar thanks - the Docker build wasn't working and a few variables needed updating. Have created a PR to your branch.

**Pull request closed without merging**
