### PR TITLE
General Refactor

### PR DESCRIPTION
**Pull request by foolishsailor**
05/04

- Home page created and barrelled
- Context and Reducers added to home
- Promptbar added context and reducer 
- Componetized the Chat/Prompt folder to Folder
- General removing of prop drilling 
- Started creating general components from code base - created Buttons folder and SidebarActionButton

06/04
- Created new Sidebar Component from common code between PromptBar and Chatbar
- Added context to both Promptbar and Chatbar
- Move any function not required on Home.tsx to related components with context.  This is a stubborn file and think best way to reduce file size of now around 700 lines is to create a fetchService and dataService to handle the localDB calls and then act as an interface to make adding external DBs easier and moving code away from file
- Added @trivago/prettier-plugin-sort-imports to auto order the file imports 

07/04
- Added reactQuery
- Added apiService
- Added errorService 
- Refactor Chat and all child componets.
- Move related functions out of Home.tsx

Next:  Finish APIservice and possibly create .actions files to hold a lot of the biz logic for some of the large components

### CODE REVIEW

**Comment by thomasleveil** [comment]
@mckaywrigley this kind of refactoring is needed. The code has grown organically thus far and it is now more error prone to make changes. While such refactoring will most likely require pending PR to be rebased, it would help keeping the code base manageable

**Comment by foolishsailor** [comment]
Had a chat with him earlier today on twitter and walked through some ideas to get a fast pass refactor to this direction.  First pass shallow dig on the hard to merge type changes like architectural etc without going too deep and then it would be easier for the community to then git into the details and tidy up.

I should be able to finish up by tomorrow night my time (UTC-0)

Let me know if there are any concerns or if there is anything specific you would like me to work on.  Main focus is disentangling components and minimizing prop drilling

**Comment by Jdban** [comment]
Do you want to get enforced prettier formatting going in this same PR? Or is that too messy. I've kinda given upon getting mine merged.

You could rip the github actouns check out of my PR (https://github.com/mckaywrigley/chatbot-ui/pull/283/files) manually by copying the `.github/workflows/prettier-check.yml` file and running `npx prettier --write .` to format the entire codebase.

**Comment by foolishsailor** [comment]
Ok another push.  Whew, things still pretty entangled but getting better.  WIll do a pass on the Chat component which is last top level component left with alot of deeply nested props.

After that can look at building some services to thin out the functions at the top level.

**Comment by foolishsailor** [comment]
Added reqctQuery and some services and currently have the API models call using - will go through app and remove all fetches into this service now

**Comment by foolishsailor** [comment]
eeek - nothing like an endless callback loop when calling a pay based API....

Racked up a quick 2.50 with of calls very quickly....OpenApi cut me off luckily...

image

**Comment by foolishsailor** [comment]
Ok large part of refactor for useContext is done.  There are still al couple of components that have a lot of business logic that need to be tidied up and get logic pulled out into services:  Home, Chat, ChatInput.

Almost there.

Could I get some eyes on this to see if I have introduced many bugs?

**Comment by mkellerman** [comment]
If you want to make a build and post the docker image, I can try it out a bit.

**Comment by thomasleveil** [comment]
@mckaywrigley maybe this is the right time to start tagging releases so that this big refactoring can be released and advertised as a beta, while new comers will still be able to deploy the latest stable release.

**Comment by mkellerman** [comment]
Yes, and SemVer the releases. Do you need help with the GitHub actions?

**Comment by foolishsailor** [comment]
> @mckaywrigley maybe this is the right time to start tagging releases so that this big refactoring can be released and advertised as a beta, while new comers will still be able to deploy the latest stable release.

Would hope we can get this merged to main relatively quickly as I don't envy the person who has to rebase this with too many further changes to main...

**Comment by Jdban** [comment]
> Would hope we can get this merged to main relatively quickly as I don't envy the person who has to rebase this with too many further changes to main...

No PRs have been merged in this repo in 3 days. I have a feeling that @mckaywrigley is working on other stuff and deprioritized this repo :/

**Comment by shep920** [comment]
Lord i would love a refactoring of index.ts

**Comment by foolishsailor** [comment]
> Lord i would love a refactoring of index.ts

its a big part of the refactor have a look at the branch 

> No PRs have been merged in this repo in 3 days. I have a feeling that @mckaywrigley is working on other stuff and deprioritized this repo :/

Im chatting with him via DM on twitter - we discussed not merging any new PRs until this refactor was complete as it will be exceptionally hard to merge otherwise

**Comment by Jdban** [comment]
> Im chatting with him via DM on twitter - we discussed not merging any new PRs until this refactor was complete as it will be exceptionally hard to merge otherwise

Awesome. Phew

**Comment by Jdban** [comment]
@mckaywrigley @foolishsailor Is there any ETA for when this will be merged?

**Pull request merged**
