### PR TITLE
Fix rendering performances issues related to scrolling events

### PR DESCRIPTION
**Pull request by thomasleveil**
## Motivation

Long conversations are triggering way too much re-renderings. In part because of the `<ReactMarkdown />` components.

This pull request is an effort to make scrolling long conversations fluid and pleasant.

## Related issues
- #184
- #205

## How to test rendering performance issues

image

----

**I'm open to any help or suggestions to make this happen**

### CODE REVIEW

**Comment by thomasleveil** [comment]
[exported_test_conversations.json.zip](https://github.com/mckaywrigley/chatbot-ui/files/11071197/exported_test_conversations.json.zip)
Here are some long conversations to import for tests

**Comment by thomasleveil** [comment]
Hi, @mckaywrigley! Can you please share your thoughts on the direction we should take with this PR ?

**Comment by mckaywrigley** [comment]
I can dive into this more once I wrap up with prompts.

Is the performance mostly just scroll speed? Haven't had a chance to test yet.

**Comment by thomasleveil** [comment]
Yes there is still something fishy with scrolling. If the conversation is
long, I 've got frame drops and framerates as low as 6 fps

Le dim. 26 mars 2023, 15:00, Mckay Wrigley ***@***.***> a
écrit :

**Comment by thomasleveil** [comment]
@mckaywrigley : I finally got results. In the end the mother of all issues was the way autoScoll was detected by having a event handler of the 'scroll' events. This was problematic because when the autoscroll was triggered it would (obviously) scroll the page down, which in turn would fire more scroll events...

## Changes
- use the intersection API to determine the autoscroll status
- use React.memo to help prevent useless components re-rendering in the chat history

**Comment by thomasleveil** [comment]
rebased on main

**Comment by mckaywrigley** [comment]
Awesome work. Just reviewed and merging in. Huge performance upgrade!

**Pull request merged**
