### PR TITLE
[WIP] Added openai import function

### PR DESCRIPTION
**Pull request by sebiweise**
- [x] Added a button to upload a OpenAI Export (conversations.json)
- [x] Map OpenAI Chats, Messages and Roles
- [ ] Import button style fix
- [ ] Match created and updated datetime

### CODE REVIEW

**Comment by mckaywrigley** [comment]
Importing from OpenAI would be super nice!

**Comment by SinanAkkoyun** [comment]
+1

**Comment by secondtruth** [comment]
@sebiweise Is this PR stil alive? Looking forward to this feature. 😊

**Comment by sebiweise** [comment]
> @sebiweise Is this PR stil alive? Looking forward to this feature. 😊

Yes, I haven't had time to work on this feature but I will have a look in the coming week👍🏼

**Pull request closed without merging**
