### PR TITLE
Feature: Support Hotkey

### LINKED ISSUE #348: Please add keyboard shortcut to start new chat.
Hi, because older chat messages will only consume tokens when starting a new topic, please add a quick way to start a new chat.

Thanks for this great app!

### PR DESCRIPTION
**Pull request by tetsujin**
This pull request adds hotkey functionality.

When you register hotkeys in Settings, you can access several features of the Chatbot UI via keyboard shortcuts.

Currently, the following hotkeys are supported

- New Conversation
- Focus Chat Input
- Delete Conversation
- Toggle Chat Bar
- Toggle Prompt Bar

Closes the following Issues
closes #348

hotkey

### CODE REVIEW

**Comment by dongphuchaitrieu** [comment]
Great work ❤️

**Comment by sachit-menon** [comment]
Would be great to get this integrated!

**Comment by Jdban** [comment]
too bad the repo is abandoned

**Comment by sachit-menon** [comment]
damn, any good alternative/fork?

**Comment by itbm** [comment]
> damn, any good alternative/fork?

https://github.com/jorge-menjivar/chatbot-ui is maintained and got some major improvements.

**Pull request closed without merging**
