### PR TITLE
Mobile UI Improvements

### PR DESCRIPTION
**Pull request by chatgpt-ai-user**
Fix parts that degrade mobile experience (only on small screens)
- Margin adjustment
 
- Remove bottom margin that appears when toggling the sidebar
(Fixed an issue where the chat on the right was not properly focused after clicking the sidebar chat list)
  
- Remove horizontal scrolling that occurs even when the sidebar is hidden (ios safari)
- etc

Please understand the awkwardness caused by the translator :)

### CODE REVIEW

**Comment by chatgpt-ai-user** [comment]
Fixed / ~ios safari issue: Problem with not focusing after chat loading in production build. It works normally in dev mode :(~

**Comment by haydenkong** [comment]
This is great!

**Comment by ivanfioravanti** [comment]
Great one!

**Comment by mckaywrigley** [comment]
Great work!!!

**Comment by secondtruth** [comment]
@chatgpt-ai-user @mckaywrigley Now the prompt input always shows this shortened text:

image

I think, it would be better to keep the longer text for the desktop version...

image

... and use the shorter one only for mobile, and switch between them conditionally.

**Comment by chatgpt-ai-user** [comment]
PR is closed so I wrote the code :)

components\chat\chat-input.tsx
```
<TextareaAutosize
  textareaRef={chatInputRef}
  className="ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring text-md flex w-full resize-none rounded-md border-none bg-transparent px-14 py-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50"
  placeholder={t(
    window.innerWidth < 768
      ? `Ask anything. Type @  /  #  !`
      : window.innerWidth < 1280
        ? `Ask anything. Type " @ "(assistants), " / "(prompts), " # "(files), " ! "(tools)`
        : `Ask anything. Type "@" for assistants, "/" for prompts, "#" for files, and "!" for tools.`
  )}
  onValueChange={handleInputChange}
  value={userInput}
  minRows={1}
  maxRows={18}
  onKeyDown={handleKeyDown}
  onPaste={handlePaste}
  onCompositionStart={() => setIsTyping(true)}
  onCompositionEnd={() => setIsTyping(false)}
/>
```

**Pull request merged**
