### PR TITLE
Add support for triggering Docker build job only when Jest tests pass

### PR DESCRIPTION
**Pull request by tatsuiman**
* Updated the on field to include a workflow_run event that triggers the build job when the Run Jest Tests workflow completes.
* Added a DATE_TAG environment variable that stores the current date in YYYYMMDD format.
* Updated the tags field of the Build and push Docker image step to include ${{ env.DATE_TAG }} and latest tags in addition to the tags extracted from metadata-action.
* The purpose of these changes is to ensure that each build is uniquely tagged with a date-based tag, while also retaining the latest tag for the most recent build. This enables you to keep a record of past builds while also making it easy to deploy the latest build.

issue https://github.com/mckaywrigley/chatbot-ui/issues/92

### CODE REVIEW

**Comment by mckaywrigley** [comment]
Going to keep this open just to have someone more familiar with Docker come look at it and make sure it's good.

**Comment by srsholmes** [comment]
Just a note, the Jest Tests are now Vitest Tests as of https://github.com/mckaywrigley/chatbot-ui/pull/257 .

I think the workflows / PR title should reflect that change.

**Comment by mckaywrigley** [comment]
Good point.

**Comment by tatsu-i** [comment]
Fixed the `Run Unit Tests` workflow to run the Docker workflow after the `Run Unit Tests` workflow passes.
Also, added repository condition like `if: github.repository == 'mckaywrigley/chatbot-ui'` to prevent Docker images from being hosted in many personal repositories.

**Comment by tatsuiman** [comment]
@srsholmes @mckaywrigley 
Is there anything else that needs to be corrected?

**Pull request closed without merging**
