### PR TITLE
styles : max width is  pretty

### PR DESCRIPTION
**Pull request by jiangxianfu**

### CODE REVIEW

**Comment by pdgxiaofei** [comment]
image
image
Hello
Please look at the two screenshots above, it seems that the adaptation of the multi-button is still not perfect.

**Comment by jiangxianfu** [comment]
> image image Hello Please look at the two screenshots above, it seems that the adaptation of the multi-button is still not perfect.

image
i can see you button, where ?

**Comment by pdgxiaofei** [comment]
This copy and edit delete button appears when you click on your conversation with the mouse.

**Comment by pdgxiaofei** [comment]
I mean, the delete button should be the same as before, it's best not to be too close to the right, otherwise the operation on the mobile will not be so perfect.

**Pull request closed without merging**
