### PR TITLE
[Bugfix] Fix a typo which leads to failure in using Plugin chat

### LINKED ISSUE #631: Error using the Google Plugin
I setup the requirements as described in the docs. Also checked via console.log in /components/Chat/Chat.tsx file. Everything' works but as soon I use the Google Plugin I got the following error: 'TypeError: selectedConversation.messages is undefined' in line 399 and an additional error/timeout in the console: 'Error: Request timed out
    at Timeout.eval [as _onTimeout] (webpack-internal:///(api)/./pages/api/google.ts:35:87)' 

Any ideas to solve that problem?

### PR DESCRIPTION
**Pull request by maddyonline**
`updateConversation` -> `updatedConversation`.

Fixes https://github.com/mckaywrigley/chatbot-ui/issues/631.

Before:

Screenshot 2023-04-29 at 2 26 13 PM

After:

Screenshot 2023-04-29 at 2 40 57 PM

### CODE REVIEW

**Comment by fredsiika** [comment]
> @maddyonline nice work. I was about to open a PR for this.

**Comment by JavaNomad** [comment]
this still needs to be updated in the current stable version.

**Comment by Ryan526** [comment]
Thank you this fixed it for me @maddyonline , is chatbot-ui no longer actively being maintained?

**Comment by Jdban** [comment]
> is chatbot-ui no longer actively being maintained?

The guy abandoned it about a month ago

**Comment by itbm** [comment]
> is chatbot-ui no longer actively being maintained?

See discussion on #682

**Pull request closed without merging**
